### ISSUE TITLE
Update to 0.6

### ISSUE THREAD

**Issue by xiongchiamiov** [docopt/docopt.rb#16]
It's been one year (and one day) since [docopt 0.6.0](https://github.com/docopt/docopt/releases/tag/0.6.0) was released (and quickly followed up by [0.6.1](https://github.com/docopt/docopt/releases/tag/0.6.1)).  I'm anxious to use the subcommand support introduced by `options_first` in Ruby, not just Python, so I have to ask - are there any plans to update this port?

**Comment by alexspeller** [comment]
New version 0.6.0 is pushed to rubygems now!
