### ISSUE TITLE
Abandoned?

### ISSUE THREAD

**Issue by sadovnik** [docopt/docopt.rb#27]
What is the state of this gem?

@arthurschreiber, @bicycle1885, @BurntSushi, @edwindj, @jaredgrubb, @johari, @kbatten, @kblomqvist, @keleshev, @kipanshi, @mboersma, @oprypin, @ryanartecona, @shabbyrobe, @voieducode.

Sorry for mass-mentioning, but we have to decide something about it.

**Comment by sadovnik** [comment]
@ryanartecona do you want to be maintainer so far? : )

**Comment by shabbyrobe** [comment]
I'm not able to do any maintenance on this port, but if you need anything from me I am at least contactable! :)

**Comment by ryanartecona** [comment]
Apologies for the delay. I am not really interested in maintaining this gem, just in getting #26 merged. :) On the other hand, what work will maintaining really require, if the python implementation hasn't seen any significant updates past 0.6.2 in over 2 years?

**Comment by alexspeller** [comment]
Docopt.rb lives! New version posted to rubygems, I'll be actively reviewing PRs and releasing etc
