### ISSUE TITLE
Example how to parse the dictionary items

### ISSUE THREAD

**Issue by E3V3A** [docopt/docopt.rb#33]
Hi @alexspeller @djmetzle !
This is a great gem and would love to see it continue living.

Can you please provide an example how to actually parse the dictionary items?  
I.e. From the examples given, how can I use/print the option variables in a different function or class? 
PS. This is my first attempt to use Ruby.

**Comment by djmetzle** [comment]
Hi @E3V3A,
   I'm not sure that learning ruby is in scope of this gem. But docopt does make it very easy to build CLI utils. Check out [this link](https://learnxinyminutes.com/docs/ruby/) for feet first ruby intro.

If you look at the [some examples](https://github.com/docopt/docopt.rb/blob/master/examples/counted_example.rb)  you'll see that the `doc` text generates the blueprint of your [dictionary](https://github.com/docopt/docopt.rb#api). The call to `Docopt::docopt` returns a `Hash` object that you can then pass around to other objects and functions.

https://github.com/docopt/docopt.rb/blob/504f310c5fd66e9f3c36b078156e5f44573ff1d3/lib/docopt.rb#L665

Hope that helps!

**Comment by E3V3A** [comment]
@djmetzle 
Thanks for your response.  I've since figured ti out and although unlikely the best way, I'm parsing this:
```ruby
  Usage:
        #{__FILE__} -r [<oauth2_token>]
```

using this:
```ruby
    options = Docopt::docopt(doc, version: VERSION)
    if options['<oauth2_token>']
           puts "Using access_token: #{access_token}"
    end
```

What is a bit weird, is that I still have to use the `<>` included in the options, instead of being undertood as signifying a template.
