### ISSUE TITLE
Maintenance status

### ISSUE THREAD

**Issue by DannyBen** [docopt/docopt.rb#38]
As I am quite dependent on the docopt gem, I was wondering if any of the collaborators is around to merge PRs?

1. I believe I have a fix for #28 
2. I would like to do some housekeeping, like
   - Gemfile/gemspec linting and common practices
   - GitHub Actions instead of Travis
   - Some updates to tests perhaps
   - Test with up to date Rubies (travis lists - 1.9.3 as the latest....)

If nobody wants to maintain this anymore, I hereby volunteer.

**Comment by alexspeller** [comment]
@DannyBen that sounds great, however I'm not an admin of the docopt organization on github. I am an owner of the gem on rubygems. Not sure if the github owners are around or available any longer for this

**Comment by DannyBen** [comment]
Thanks @alexspeller - trying to figure out if it is time to switch to a fork, or is there still a chance to get this back on track.

**Comment by DannyBen** [comment]
Well - I have [switched to my own fork](https://github.com/DannyBen/docopt_ng). If at any time someone wants to grant access to more maintainers, or releasers, or to merge PRs, I am happy to contribute.
