### ISSUE TITLE
Bad error string when no argument specified for required short option

### ISSUE THREAD

**Issue by VorontsovIE** [docopt/docopt.rb#9]
When I include this line in doc-string: "-e --extension EXT  Extension of output files"
And use short-option -e without a parameter, then I get error-string: "-- requires argument", so that I can't realize which option have an error. I'd prefer error string "-e requires argument" or at least "--extension requires argument"

**Comment by alexspeller** [comment]
Closing old issue, anyone still experiencing this feel free to open a new issue
